### ISSUE TITLE
Getting issues on building or installing the xmlrpc-scan

### ISSUE THREAD

**Issue by hunter0x8** [nullfd/xmlrpc-scan#1]
Other golang tools are working fine and installing fine got issue with this can you please guide what is the issue
![image](https://user-images.githubusercontent.com/46222314/83590428-26417b80-a56f-11ea-9d4c-fd667daaacfa.png)
 Tried build or run from the source code but still getting this error

**Comment by devpwn** [comment]
it's because i dont use imports from another repository.. soo go get wont work.. u can download from releases or build by yourself (best option) see the README =).

**Comment by hunter0x8** [comment]
Ok thank you! for clarifying let me give it a try.

**Comment by hunter0x8** [comment]
Thankyou Figure it out.
